#!/bin/bash

. /etc/default/gatherip

if [ "$2" == up ]; then
    mail -a "From: $FROM" -s "[$TAG]$(hostname --fqdn)" $TO <<EOF
$1 $(wget http://ipecho.net/plain -O - -q):$(netstat -anp -t tcp|grep 'LISTEN *[0-9]*/sshd'|grep -oE ':[0-9]+'|cut -c2-|sort -n -u|awk '{printf("%s ",$0)} END {printf("\n")}') $(hostname --fqdn)
EOF
fi
